using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TopluMailGonderme
{
    public class ArrayClass
    {
        //Burayı hiç ellemeyin 
        public string[] mailAdresleri = new string[]// kişilerin mail adresleri
        {
"muhammetakgoz@gmail.com",
"ademeg_42@hotmail.com",
"akabar93@gmail.com",
"sumeyyegun167@gmail.com",
"fatoss.dogn@gmail.com",
"asimtahirbilgi@gmail.com",
"halimeeakcin@gmail.com",
"nurgulsen8392@gmail.com",
"ibrahimodev42@gmail.com",
"tuncerbostancibasi@gmail.com",
"aliekber123kara@gmail.com",
"omerkonya1987.17@gmail.com",
"ahmetparpucu1994@gmail.com",
"veyselceren25@gmail.com",
"ismail.u.avci@gmail.com",
"bilaleken4442@gmail.com",
"firatdemir997@gmail.com",
"berben9808@gmail.com",
"tanahsen35@gmail.com",
"saadetsena16@gmail.com",
"ayseee.simseeek.98@outlook.com",
"emrahf23@gmail.com",
"nurhan-uzun@hotmail.com",
"bilgisayar_konya@hotmail.com",
"kayaakader26@gmail.com",
"hd.hilaldemirci@gmail.com",
"duyguataseveer@gmail.com",
"yeg2799@gmail.com",
"ersenkele@gmail.com",
"mustafatopcu907@outlook.com",
"rdgnatakan@gmail.com",
"ahmtknt46@gmail.com",
"yyusuf0441@gmail.com",
"kayagulsum@yahoo.com",
"reginamndi@gmail.com",
"rabiakuran34@gmail.com",
"ozgurnurettinozturk@gmail.com",
"aytac4196@gmail.com",
"zinebzellak@gmail.com",
"kubra.kaya684@gmail.com",
"gs_okkesyetim_1998@hotmail.com",
"beyzadeniz25187875@gmail.com",
"enisyl13@gmail.com",
"nanoteksunum@gmail.com",
"omerbh221@gmail.com",
"zhvarol16@gmail.com",
"probx8021@gmail.com",
"yorulmazfrt@gmail.com",
"mazlumbaydar@gmail.com",
"berben9808@gmail.com",
"yy3474@gmail.com",
"kucukdogrumerve@gmail.com",
"sariaysegulll@gmail.com",
"kaymaznazli4321.1@gmail.com",
"rumeysa271946@gmail.com",
"saadetsena16@gmail.com",
"aliozten92@gmail.com",
"elifgenc728@gmail.com",
"haleurun19@gmail.com",
"akhundlu25@gmail.com",
"fatih.batuge@hotmail.com",
"seda.taskin@voltmotor.com.tr",
"sukrutas99@gmail.com",
"candemir07@gmail.com",
"aysel.abbasova19@gmail.com",
"zbkocaman@gmail.com",
"seda__0211@outlook.com",
"rabistaa@gmail.com",
"fisun.sarikaya@gmail.com",
"uemre.deger@gmail.com",
"berben9808@gmail.com",
"ramazan.demir@outlook.com.tr",
"elif.parlak004@gmail.com",
"zeynepolmirac@gmail.com",
"c_gunduz@hotmail.com",
"c_gunduz@hotmail.com",
"hrysn108@gmail.com",
"hasret.kalhann@gmail.com",
"omer_kazanci@outlook.com",
"didem-eryasar@hotmail.com",
"busraaktas38@hotmail.com",
"eneskocer161@gmail.com",
"aysedinc0001@gmail.com",
"aysedinc0001@gmail.com",
"mahmutsamieroglu@gmail.com",
"oguzhanakball@hotmail.com",
"4rslanismet@gmail.com",
"akilic1453@hotmail.com",
"ranadudukabak@gmail.com",
"aktasceren@outlook.com",
"elif.muslu97@hotmail.com",
"yasinbulgan1995@gmail.com",
"mehmet_ciklacandir@hotmail.com",
"mustafakocboun@gmail.com",
"mineyldrm63@gmail.com",
"h.ibrahim2321@gmail.com",
"ismail.eris@boer.com.tr",
"metealperenn@gmail.com",
"saaydmr@gmail.com",
"fthaslan16@gmail.com",
"bugrahann1496@gmail.com",
"kaktimurf@gmail.com",
"c_gunduz@hotmail.com",
"ebru592017@hotmail.com",
"mehmet_ciklacandir@hotmail.com",
"muhammedmustafagoktas@outlook.com",
"yusuferkoc99@gmail.com",
"miraykol99@gmail.com",
"fatihkilictr58@gmail.com",
"y.tekin@sinop.bel.tr",
"harmanayda@gmail.com",
"omerhankaplann@gmail.com",
"nurtenagn@gmail.com",
"omergokcee1@gmail.com",
"yasard481@gmail.com",
"handan_altuner@hotmail.com",
"caglarcansarikaya@hotmail.com",
"berben9808@gmail.com",
"ilke.gnc@gmail.com",
"yahyadogru21@gmail.com",
"oabekdik@gmail.com",
"kubra.selcuk01@gmail.com",
"oktaykara6565@gmail.com",
"serbeyerbey@gmail.com",
"sedeferbey@gmail.com",
"furkanylmz357@gmail.com",
"dilaragamzec@gmail.com",
"bbusebtn.10@gmail.com",
"idrisibrahimerten@gmail.com",
"ihsanlevent1@gmail.com",
"yucelalican@hotmail.com",
"gizemonar20@gmail.com",
"oktayyozbekk@gmail.com",
"ugurhanatilgan@gmail.com",
"aycanur15@gmail.com",
"mertnler113@gmail.com",
"mertnler113@gmail.com",
"yyusuf0441@gmail.com",
"ayberktsl@gmail.com",
"eraykisabacak@hotmail.com",
"irem3106@gmail.com",
"aysunkoylu52@gmail.com",
"erkanibrahim99@gmail.com",
"zynpylmz537@gmail.com",
"tugbademiiralp@outlook.com",
"bilalyildiz.28@gmail.com",
"oktayhalitekinay@gmail.com",
"bekirgol20@gmail.com",
"esma.koc@ogr.iuc.edu.tr",
"gnceitir96@hotmail.com",
"talhaaaagul0660@gmail.com",
"kahilmehmetali@gmail.com",
"g.201_@hotmail.com",
"bbusebtn.10@gmail.com",
"elifnurceto@gmail.com",
"zehrabetulgundogdu@outlook.com",
"engineertugrul@gmail.com",
"talhaaaagul0660@gmail.com",
"beyzanurozdemir1998@gmail.com",
"muhammetsefatopuz@gmail.com",
"iremicyer@gmail.com",
"ahmet.bozdag@itelligence.com.tr",
"iremmnursagin@gmail.com",
"haticeoz@haticeoz.com",
"qwertas2@hotmail.com",
"seydatas14@gmail.com",
"handanyarici@gmail.com",
"kybr7@gmail.com",
"ahmetomer2634@gmail.com",
"sinanduman646@gmail.com",
"zeynepyarenala@gmail.com",
"eliftkcann@gmail.com",
"sb.btrbk@gmail.com",
"cakmakyunus138589@gmail.com",
"nurmelu@gmail.com",
"furkanakpinar34614@gmail.com",
"mevaberfin@gmail.com",
"haliliboekici14@gmail.com",
"zeryoldas27@gmail.com",
"melisgulerg@gmail.com",
"eayurdakok@gmail.com",
"elifcetin9832@gmail.com",
"semihanr012@gmail.com",
"melsijensen01@gmail.com",
"dmrbas.aysee@gmail.com",
"ygtacet@gmail.com",
"omerzgun@gmail.com",
"aahmetdrsn1@gmail.com",
"nejda.yildiz@gmail.com",
"cagnur__caliskan@hotmail.com",
"beyzanurceylannn@gmail.com",
"wmehmetercanx6346@gmail.com",
"nasim.rafat72@gmail.com",
"melihdemir907@gmail.com",
"brkyakdemir@gmail.com",
"18061514@stu.omu.edu.tr",
"caglarcansarikaya@hotmail.com",
"kaandemircan97@gmail.com",
"oguzhanylmz5372@gmail.com",
"beyzadeniz25187875@gmail.com",
"burakdinc__gul@hotmail.com",
"iremmnursagin@gmail.com",
"eslemaysen@gmail.com",
"beytullahmurat7@gmail.com",
"serdargurkan77@gmail.com",
"cuce123alper@hotmail.com",
"yucemeneks@gmail.com",
"cuce123alper@hotmail.com",
"cuce123alper@hotmail.com",
"susamummugulsum@gmail.com",
"susamummugulsum@gmail.com",
"rukiyealc99@gmail.com",
"semihanr012@gmail.com",
"gnlsvr8@gmail.com",
"ebrarcoskun624@gmail.com",
"fathtrnk.53@gmail.com",
"muhammedsalihgarip@gmail.com",
"afewmovies@gmail.com",
"tnursahatov@gmail.com",
"esra_4561972@outlook.com",
"ygtacet@gmail.com",
"abdulla001753@gmail.com",
"aminenur.tunc@gmail.com",
"btlkrmn220@gmail.com",
"hezarfenadiyaman@gmail.com",
"ramaznalbustanli@gmail.com",
"doganatli1@hotmail.com",
"zynparpck@gmail.com",
"akadir.baspinar@gmail.com",
"yildirimgulsah2323@gmail.com",
"dy19031507@gmail.com",
"sezeryilmaz1770@gmail.com",
"ebrarcoskun624@gmail.com",
"burhanaydogdu30@gmail.com",
"gamzeceri@icloud.com",
"hafizeacar05@gmail.com",
"hafizeacar05@gmail.com",
"ozge.gidiz@gmail.com",
"mervekucukcaglar15@gmail.com",
"ahmetomer2634@gmail.com",
"azizeatar@yandex.com",
"alkinelifesma@gmail.com",
"ebrarcoskun624@gmail.com",
"oguzhanylmz5372@gmail.com",
"Gamzeerkek2@gmail.com",
"ahmetmutlu1907@hotmail.com",
"ebrarcoskun624@gmail.com",
"anozalp@gmail.com",
"sebahatnurozcan3737@gmail.com",
"sedanurozcan047@gmail.com",
"gencer.varol@outlook.com",
"ali.tarik.15@hotmail.com",
"Cikrikciismail7@gmail.com",
"seyityldz5@gmail.com",
"bariskan.adem@gmail.com",
"ahmetuguz09@gmail.com",
"beytullahmurat7@gmail.com",
"erarslanmehmetcan@gmail.com",
"abayomer1905@gmail.com",
"zeyneptetik2@gmail.com",
"abayomer1905@gmail.com",
"190224006@kocaeli.edu.tr",
"konukmehmetburak@gmail.com",
"selinzbk@yandex.com",
"mailsiberavci@gmail.com",
"star186v@gmail.com",
"oguzhaniptes02@gmail.com",
"salihaipts@gmail.com",
"hacerkubra96@gmail.com",
"brkntut@gmail.com",
"yavuzselimtsc@outlook.com",
"halilkaragoz408@gmail.com",
"furkanakpinar34614@gmail.com",
"ziya@onal.net",
"humeyracimen2001@gmail.com",
"aydonerahmethakan@gmail.com",
"yusufsazil1453@gmail.com",
"info@caglar-celik.com",
"tolgaozek@gmail.com",
"ozgur.guvercin@kiyiemniyeti.gov.tr",
"ebrarcoskun624@gmail.com",
"metehan202524@gmail.com",
"alpertrkmn48@gmail.com",
"haskenan34@gmail.com",
"haskenan34@gmail.com",
"krst1338@gmail.com",
"ozer.hhakan@gmail.com",
"Rahmiebrarguccan@gmail.com",
"gokhantatlicilar@gmail.com",
"gecermehmet3796@gmail.com",
"berbub19@gmail.com",
"ceo.hrn.yildirim@gmail.com",
"dorukmalgir@gmail.com",
"190224006@kocaeli.edu.tr",
"f191202094@ktun.edu.tr",
"simge95ilgim@gmail.com",
"kadriye488@gmail.com",
"oktayyildiz220@gmail.com",
"gecermehmet3796@gmail.com",
"ebrarcoskun624@gmail.com",
"uzun3535musa@gmail.com",
"sinan.samur.emm@hotmail.com"



        };


        public string[] isimler = new string[]// kişilerin isimlerİ,
        {
"Muhammet Akgöz",
"Adem Emre Gökmen",
"Nevzat Anıl Kabar",
"Sümeyye Gündoğdu",
"Fatma Doğan",
"Asım Tahir KARAKUŞ",
"Halime Akçin",
"NURGÜL ŞEN",
"İbrahim ÖDEV",
"Tuncer Bostancı",
"Ali Ekber KARA",
"Ömer Uçkun",
"Ahmet Parpucu",
"Ceren Turgut",
"İsmail Avcı",
"Bilal Eken",
"Fırat Demir",
"Berfin Nur Temur",
"Ahsen Tan",
"SAADET SENA ÇİNTİMUR",
"Ayşe ŞİMŞEK",
"Emrah Hanifi Fırat",
"Nurhan Uzun",
"Zehra Özdeğirmenci",
"Kadriye Kızılkaya",
"Hilal Demirci",
"Duygu Atasever",
"Yunus Emre Guzel",
"Ersen FİLİZ",
"Mustafa Topcu",
"Atakan Erdoğan",
"Ahmet Kanat",
"Yusuf Yıldız",
"Gülsüm Kaya",
"Hanzade Erdoğan",
"Rabia Kuran",
"Özgür Nurettin Öztürk",
"Ömer Aytaç",
"Zineb Zellak",
"Seher Kübra Kaya",
"ÖKKEŞ YETİM",
"Beyza Deniz",
"Enis Yaylagül",
"Kaan DEMİROK",
"Ömer Bahtiyar Bıdak",
"Zeynep Hilal VAROL",
"Can",
"Fırat Yorulmaz",
"Mazlum BAYDAR",
"Berfin Nur Temur",
"Yunus Yılmaz",
"Merve KÜÇÜKDOĞRU",
"Ayşegül Sarı",
"Nazlı Kaymaz",
"Rümeysa Abacı",
"Saadet Sena Çiintimur",
"Ali ÖZTEN",
"Elif Genç",
"Hale Taşdelen",
"Ilkin Akhundlu",
"Fatih Batuge",
"Seda Taşkın",
"Şükrü Taş",
"Can Demir",
"Aysel Abbasova",
"Zeynep Kocaman",
"Seda A.",
"Rabia Taş",
"Funda Füsun Sarıkaya",
"Ufuk Değer",
"Berfin Nur Temur",
"Ramazan DEMİR",
"Elif parlak",
"ZEYNEP MİRAÇ OL",
"Çiğdem Gündüz",
"Çiğdem Gündüz",
"Huriye Şen",
"Hasret Kalhan",
"Ömer Kazancı",
"Didem Eryaşar",
"Busra Aktas",
"Enes koçer",
"Ayşe DİNÇ",
"Ayşe DİNÇ",
"MAHMUT SAMİ EROĞLU",
"Oğuzhan Akbal",
"İsmet Arslan",
"Ali KILIÇ",
"Rana Dudu Kabak",
"Ceren Aktaş",
"Elif Muslu",
"Yasin Bulgan",
"Mehmet Çıklaçandır",
"Mustafa Koç",
"Mine YILDIRIM",
"Halil İbrahim Annadınç",
"İsmail Eriş",
"Mete Alperen BAĞRIAÇIK",
"Sarp Abdurrahman Aydemir",
"Muhammet Fatih Aslan",
"Buğrahan Çakır",
"Ferit Kaktimur",
"Çiğdem Gündüz",
"Ebru Betül KUYU",
"Mehmet Çıklaçandır",
"Muhammed Mustafa Göktaş",
"Yusuf Erkoç",
"Miray KOL",
"Fatih Kılıç",
"Yasin Tekin",
"Ayda Harman",
"Ömerhan KAPLAN",
"Nurten Akgün",
"Ömer Gökçe",
"Doğukan Yaşar",
"Handan Altuner",
"Çağlar Can Sarıkaya",
"Berfin Nur Temur",
"İlke Genç",
"Yahya Doğru",
"Onur Ali Bekdik",
"Kübra Selçuk",
"Oktay Kara",
"S. Selahattin Erbey",
"SEDEF ERBEY",
"Furkan YILMAZ",
"Dilara Gamze Çalışkan",
"Buse Batan",
"İdris İbrahim Erten",
"İhsan Levent",
"Ali Can Yücel",
"Gizem Onar",
"Oktay Özbek",
"Uğur han ATILGAN",
"Ayça Nur Demir",
"Mert Ünlüer",
"Mert Ünlüer",
"Yusuf Yıldız",
"Hakkı Ayberk Tasalı",
"Ali Eray Kısabacak",
"İrem ENGİNAR",
"Aysun Koylu",
"İbrahim Erkan",
"Zeyneo Yılmaz",
"Tuğba Demiralp",
"Bilal Yıldız",
"Oktay Halit Ekinay",
"Bekir Göl",
"Esma Koç",
"Itır Günce Mülayim",
"Talha Gül",
"Mehmet Ali Kahiloğulları",
"Gökay Çelik",
"Buse Batan",
"Elifnur Çeto",
"Zehra Betül GÜNDOĞDU",
"Ertuğrul Furkan Zengin",
"Talha Gül",
"Beyzanur Özdemir",
"Muhammet Sefa Topuz",
"İrem İçyer",
"Ahmet Bozdağ",
"İrem Nur Sağın",
"Hatice Öz Pektaş",
"Salih Fere",
"Şeyda Taş",
"Handan Yarici",
"Kübra Kaya",
"Ahmet Ömer Erdem",
"SİNAN DUMAN",
"Zeynep Yaren Ala",
"Elif",
"Saliha Betul Batırbek",
"Yunus",
"Nazmiye Nur Melahat Uçucu",
"Furkan Akpınar",
"Berfin Meva Arslan",
"Halil İbrahim EKİCİ",
"Zehra ERYOLDAŞ",
"Melis GÜLER",
"Ezgi Arzu Yurdakök",
"ELİF ÇETİN",
"Semiha Nur Küçükdoğru",
"Melis Karadağ",
"Ayşe DEMİRBAŞ",
"Yiğit Acet",
"Ömer Özgün",
"Ahmet Dursun",
"Nejda Yıldız",
"Çağnur Çalışkan",
"Beyza Nur Ceylan",
"Mehmet Ali Ercan",
"Muhammed Nasim ZAHEROGHLI",
"Melih Demir",
"Berkay Akdemir",
"Kùbra TÙRKMEN",
"Çağlar Can Sarıkaya",
"Kaan DEMİRCAN",
"Oğuzhan Yılmaz",
"Beyza Deniz",
"Burak Dinç",
"İrem Nur Sağın",
"Eslem Ayşen",
"Beytullah Murat",
"Serdar Gürkan Çetinkaya",
"Alper CÜCE",
"Menekşe Yüce",
"Alper CÜC3",
"Alper CÜCE",
"Ümmügülsüm Susam",
"Ümmügülsüm Susam",
"Rukiye ALICI",
"Semiha Nur Küçükdoğru",
"Gönül İpeksever",
"Ebrar Coşkun",
"Fatih TIRNIK",
"Salih Garip",
"Züleyha Kahraman",
"Toyly Nursahatov",
"Esra Topbaş",
"Yiğit Acet",
"ABDULLAH DOL",
"Aminenur Tunç",
"Betül Karaman",
"Ahmet Adıyaman",
"Ramazan Albustanlı",
"Doğan Atlı",
"Zeynep Arpacık",
"Abdulkadir Başpınar",
"Gülşah yıldırım",
"Derya Yıldırım",
"Sezer Yılmaz",
"Ebrar Coşkun",
"Burhan AYDOĞDU",
"Gamze Çeri",
"Hafize ACAR",
"Hafize ACAR",
"Özge Gidiz",
"Merve Küçükçağlar",
"Ahmet Omer Erdem",
"Lemis ATAR",
"Elif Esma Alkın",
"Ebrar Coşkun",
"Oğuzhan YILMAZ",
"Gamze ERKEK",
"Ahmet Mutlu",
"Ebrar Coşkun",
"Ahmet Nusret ÖZALP",
"Sebahat Nur Özcan",
"Sedanur Özcan",
"Gencer Varol",
"Ali Tarık Yönet",
"İsmail Çıkrıkçı",
"Seyit YILDIZ",
"Adem Gürhan BARIŞKAN",
"Ahmet Uğuz",
"Beytullah Murat",
"Mehmetcan Erarslan",
"Ömer Abay",
"Zeynep Tetik",
"Ömer Abay",
"Bayram DENİZ",
"Mehmet Burak Konuk",
"Selin  Özbek",
"Burak AVCI",
"Vedat Yiğit",
"Oğuzhan İpteş",
"Saliha İpteş",
"Kübra Kılıç",
"Berkan Tüt",
"Yavuz Selim Taşçı",
"Halil Karagöz",
"Furkan Akpınar",
"Ziya ÖNAL",
"HÜMEYRA ÇİMEN",
"Ahmet Hakan Aydöner",
"Yusuf SAZİL",
"Çağlar Çelik",
"Tolga Özek",
"Özgür Güverçin",
"Ebrar Coşkun",
"Metehan Çetin",
"Alper Türkmen",
"Kenan Has",
"Kenan Has",
"Kürşat Şimşek",
"Hakan Mzer",
"Rahmi Güccan",
"Gökhan Tatlıcılar",
"Mehmet Geçer",
"Berke KENESARI",
"HARUN YILDIRIM",
"Doruk Dilaver Malgir",
"Bayram DENİZ",
"İbrahim Abbasi",
"Simge ılgım horat",
"Ecrin Kadriye Katipoğlu",
"Oktay Yıldız",
"Mehmet Geçer",
"Ebrar Coşkun",
"Musa Uzun",
"Sinan Samur"



        };
    }
}
